### ISSUE TITLE
.gitignore 사용.

### ISSUE THREAD

**Issue by Untitled0828** [GoLani11/GoLani_ModPack#1]
깃헙은 dll, exe등 이런 파일이 올라가면 경고를 보냅니다.
그래서 .gitignore를 사용해서 깃헙에 푸시 안되야 되는 파일들을 지정할 수 있습니다.
빌드 가 된 폴더인 bin등은 권장하지 않는 부분입니다.

https://www.toptal.com/developers/gitignore/api/visualstudio,csharp

visualstudio, csharp에서 필요 없는 것만 추가한 파일입니다. 이것만 최상단에 넣어주시면 됩니다.

커스텀을 원하시면 https://www.toptal.com/developers/gitignore/ 여기에서 선택해서 만들어주시면 됩니다.

게시글에 댓글로 남기자니 뭔가 어울리지 않아서 이슈페이지로 올렸습니다.

**Comment by GoLani11** [comment]
아 맞네요. 제가 프로그램 만드는 것에만 집중하다보니 잊고 있었네요. 자세한 설명 감사드리고 항상 알려주셔서 감사합니다!
